name: MSFthegame.org
favicon: null
layout_spectrum: 0.43968487507663667
typography_spectrum: 0.35441
title: MSF The Game
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ed1b24'
    - '#0a0a0a'
    - '#84736c'
    - '#fd678d'
  brandStrength: 0.06905726343393326
  lightness: 1
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
